export const LOCATION_LOADING = 'LOCATION_LOADING';
export const LOCATION_LOAD_SUCCESS = 'LOCATION_LOAD_SUCCESS';
export const LOCATION_LOAD_FAIL = 'LOCATION_LOAD_FAIL';

export const JOB_LOADING = 'JOB_LOADING';
export const JOB_LOAD_SUCCESS = 'JOB_LOAD_SUCCESS';
export const JOB_LOAD_FAIL = 'JOB_LOAD_FAIL';


